name: Flutter APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Descargar la última versión estable de Flutter
          wget https://storage.googleapis.com/download.flutter.io/flutter_linux_3.7.0-stable.tar.xz
          
          # Extraer y mover Flutter a la carpeta adecuada
          tar xf flutter_linux_3.7.0-stable.tar.xz
          sudo mv flutter /opt/
          
          # Configurar las variables de entorno
          export PATH="/opt/flutter/bin:$PATH"
          
          # Ejecutar flutter doctor para verificar la instalación
          flutter doctor

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
