name: Migrate Flutter Project

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Create new Flutter project
        run: |
          flutter create -t app new_project

      - name: Move Dart code and assets to new project
        run: |
          cp -r lib new_project/lib/
          cp -r assets new_project/assets/
          cp pubspec.yaml new_project/pubspec.yaml

      - name: Install dependencies
        run: |
          cd new_project
          flutter pub get

      - name: Run Flutter app (to ensure everything works)
        run: |
          cd new_project
          flutter run --no-sound-null-safety
